name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install poetry
          poetry install
          python -c "import sys; print(sys.version)"
          pip list

      - name: Poetry Build
        run: |
          . venv/bin/activate
          poetry build

      - name: Test Build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl

          flameshow --version

      - name: Upload to Pypi
        env:
          PASSWORD: ${{ secrets.FLAMESHOW_PYPI_TOKEN }}
        run: |
          . venv/bin/activate
          poetry publish --username __token__ --password ${PASSWORD}
